version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "xlsx2cfLambdaStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2e3n8tjtohv8"
s3_prefix = "xlsx2cfLambdaStack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
profile = "personal"
